### ISSUE TITLE
hook stripe into quickbooks

### ISSUE THREAD

**Issue by brunosardinepi** [brunosardinepi/pagefund#244]

**Comment by brunosardinepi** [comment]
@dmortazavi did Mona say she did this?

**Comment by dmortazavi** [comment]
Spoke to Mona and we need to figure out what connector app we want to use to tie in stripe to QB online. working on this today and tomorrow

**Comment by dmortazavi** [comment]
Zapier can add a new sales receipt for each charge made via stripe (https://zapier.com/apps/quickbooks/integrations/stripe)

We may not need this, however. Our primary use during the beginning stages of the company will be to track profits and losses during the beginning stages. If stripe deposits daily into our account, Quickbooks online should pick this up as a deposit into our account. Depending on how the P&L tracking works in QBO, we may be fine with just this.

QBO also offers an API that garrett can leverage if it comes down to it https://developer.intuit.com/docs/00_quickbooks_online/5_api_reference/00_overview

**Comment by dmortazavi** [comment]
Deposited funds into page fund account via donation to our page. waiting on it to populate in chase bank act and QB before making a decision on if this is needed

**Comment by dmortazavi** [comment]
Another potential application will be sush.io (http://sush.io/apps)

Each are $20 and will allow us to sync Stripe with QB Online.

such.io allows 100 free transactions before you have to subscribe. I started the test and see, in QBO, the 6 transactions we made when testing. i need to review this with mona to make sure I'm on the right track

**Comment by dmortazavi** [comment]
after further review, no need to hook strip to QBs. we will use the QB bank deposit info and the export function of the payment section of Stripe when tax time rolls around
