### ISSUE TITLE
"how-to" pages

### ISSUE THREAD

**Issue by brunosardinepi** [brunosardinepi/pagefund#261]
@dmortazavi will do content

**Comment by dmortazavi** [comment]
I got this one

**Comment by dmortazavi** [comment]
content here https://docs.google.com/document/d/1-YJqJ-tDbu8BiG-N7OPSaAMXv-oW2Pf1BD3Wu5ZNaQc/edit?usp=sharing

Our Story will go when you scroll on the home page. Scroll from the initial homepage down to see a stock photo, then the Our Story 

Get started, how it works, and features will all be separate pages. there will be links to these in the footer of the website, as well as buttons under the Our Story 

I will work on FAQs
