### ISSUE TITLE
spelling/grammar check

### ISSUE THREAD

**Issue by brunosardinepi** [brunosardinepi/pagefund#280]

**Comment by dmortazavi** [comment]
When on a Page, the link for "create campaign" does not have the C capitalized in campaign. It should read "Create Campaign"

Need to change "Tweet it" to "Share on Twitter"

All other spelling and grammar correct as of now

**Comment by brunosardinepi** [comment]
for future reference: http://www.thepunctuationguide.com/period.html

**Comment by dmortazavi** [comment]
passed to my cousin for review

**Comment by dmortazavi** [comment]
first round of notes here. she will continue to work on "our story" and FAQs 

https://docs.google.com/document/d/1qn308EoXbN2rCqjm3p55GINxA1HDyBwkfvjGgDvZGEw/edit?usp=sharing

**Comment by brunosardinepi** [comment]
complete, merged to master
