### ISSUE TITLE
test website render in all modern browsers and devices

### ISSUE THREAD

**Issue by brunosardinepi** [brunosardinepi/pagefund#291]

**Comment by dmortazavi** [comment]
testing as of #213 

Testing rendering of the following parameters:
- Homepage 
- Page 
- Title bar
- Terms of Service
- Privacy Policy
- Overall feel

Completed Results for OS and browser:

Mac
- Safari - Success
- Chrome - Success
- Firefox - Success

Windows
- Edge - Success
- Chrome - Success
- Firefox - Success (when displayed on top sites, it reads "page" instead of "pagefund". Non-priority for now)

**Comment by brunosardinepi** [comment]
@dmortazavi think this is ready for the final pass, pls do

**Comment by dmortazavi** [comment]
Testing rendering of the following parameters:

Homepage
Page
Title bar
Terms of Service
Privacy Policy
Overall feel
Completed Results for OS and browser:

Mac

Safari - Success
Chrome - When clicking onto the homepage for the first time (or navigating back to it from another location on the site), there is a split second where the logo is huge and out of proportion before going to normal
Firefox - Success


Windows - will complete later today or tomorrow

**Comment by dmortazavi** [comment]
All windows desktop browsers rendered extremely well. Only the known issue above persists for each browser: When clicking onto the homepage for the first time (or navigating back to it from another location on the site), there is a split second where the logo is huge and out of proportion before going to normal

Will test mobile shortly on android and iOS

**Comment by brunosardinepi** [comment]
image glitch resolved in latest dev version

**Comment by brunosardinepi** [comment]
dustin finishing up tonight

**Comment by dmortazavi** [comment]
Completed iOS testing on safari and chrome. Only apparent issue is that voting participants pictures appear as broken. i uploaded them via chrome for iOS and the pics were straight from my camera roll

**Comment by dmortazavi** [comment]
completed testing on an android device. all looks good there. just the above issue with the voting participant pics in iOS

**Comment by brunosardinepi** [comment]
broken picture issue resolved
