### ISSUE TITLE
check site titles on all pages

### ISSUE THREAD

**Issue by brunosardinepi** [brunosardinepi/pagefund#301]

**Comment by brunosardinepi** [comment]
@dmortazavi post any changes in here

**Comment by dmortazavi** [comment]
Trying to keep as simple as possible on the title pages. Too much up there is distracting 

Homepage: PageFund
About/FAQs/Howto: About | PageFund
Terms of Service/Privacy Policy: Terms | PageFund
Get Started/Create: Create | PageFund
Create Page: Create Page | PageFund
Create Campaign: Create Campaign | PageFund
Search: Search | PageFund
Signup: Signup | PageFund
Login: Login | PageFund
Donate to a Page/ General Campaign: Donate | PageFund
Donate to a Voting Campaign: Vote | PageFund
Profile: Profile | PageFund
Upload images: Upload | PageFund
Print history for tax purposes: Donation History | PageFund
Page: [Page Name up to 25 characters] | PageFund
Campaign: [Campaign Name up to 25 characters] | PageFund
Dashboard Page/Campaign: Dashboard | PageFund
Editing a Page/Campaign: Edit | PageFund
Invite users/managers/admins: Invite | PageFund
Sharing via FB/twitter/etc..: Share | PageFund

**Comment by brunosardinepi** [comment]
we haven't made any new pages and any pages in the future will be built with this simplicity in mind.
