### ISSUE TITLE
feature page

### ISSUE THREAD

**Issue by brunosardinepi** [brunosardinepi/pagefund#344]
optional, dependent on content from @dmortazavi

**Comment by dmortazavi** [comment]
being worked on here https://docs.google.com/document/d/1-YJqJ-tDbu8BiG-N7OPSaAMXv-oW2Pf1BD3Wu5ZNaQc/edit?usp=sharing

**Comment by dmortazavi** [comment]
I added this into the FAQs between questions 3 and 4

How can I verify my Page?
Verifications are available for any 501(c)(3) registered organization. To get verified, tweet at us from your twitter account or email us at help@page.fund and include your name, website, and the title of your position. Please allow 48-72 hours for us to complete our verification. Once we do, you will see a verification check mark on your Page!

**Comment by brunosardinepi** [comment]
complete, merged to master
