### ISSUE TITLE
show our fees

### ISSUE THREAD

**Issue by brunosardinepi** [brunosardinepi/pagefund#345]
and change from 5% to 4.8%

**Comment by brunosardinepi** [comment]
@dmortazavi tell me where to put this

**Comment by dmortazavi** [comment]
I think it should go on our features page. i don't think it would be best to have a whole page dedicated to it. being worked on here https://docs.google.com/document/d/1-YJqJ-tDbu8BiG-N7OPSaAMXv-oW2Pf1BD3Wu5ZNaQc/edit?usp=sharing

**Comment by brunosardinepi** [comment]
goes on #344

**Comment by brunosardinepi** [comment]
completed in #344
