### ISSUE TITLE
Code verification logo 

### ISSUE THREAD

**Issue by dmortazavi** [brunosardinepi/pagefund#355]
Below is from our FAQ page and is how we will verify Pages for the time being. Need to have Garrett code in the logo itself. I think we should use this one: https://fontawesome.com/icons/check-circle?style=light

"Verifications are available for any 501(c)(3) registered organization. To get verified, tweet at us from your twitter account or email us at help@page.fund and include your name, website, and the title of your position. Please allow 48-72 hours for us to complete our verification. Once we do, you will see a verification check mark on your Page!"

**Comment by brunosardinepi** [comment]
code logic is done and faq is added to prod
