### ISSUE TITLE
live page test

### ISSUE THREAD

**Issue by brunosardinepi** [brunosardinepi/pagefund#388]
adding bank account and donating

**Comment by dmortazavi** [comment]
Scenario:
- created a page with real info, but fake bank and SSN
Result: 
- got error from PF

Scenario:
- created a page with real info, real bank info, but fake ssn. 
Result:
- got a safari failed to open page error. so a safari error, not a pagefund error
- Notes from here: I pressed the back button in my browser and it took me back to the bank info page. I used the correct SSN and then put a fake bank acct. it created a page. the page has the correct bank acct (not the one I faked the second go around)

**Comment by brunosardinepi** [comment]
created a donation to a page with a custom amount ($1), no extra options chosen, manually entered my credit card info, and i selected "save card". donation was successful

![2018-02-06 22_20_02-balance _ overview](https://user-images.githubusercontent.com/22970115/35898384-026a5eea-0b8c-11e8-8a1f-2962c87aabcd.png)
![2018-02-06 22_19_24-payment ch_1bskloalnjdwhqvyfmpxke5n](https://user-images.githubusercontent.com/22970115/35898385-027c6a22-0b8c-11e8-9dbd-ac96c9d77300.png)

**Comment by dmortazavi** [comment]
Created another page will all valid info except SSN and stripe shows the act as pending 

Created another page with all correct info. all was successful but no confirmation email was received

**Comment by dmortazavi** [comment]
Need to have a "back" button on pages 2-4 of the page creation process
- opened #408
