### ISSUE TITLE
live general campaign test

### ISSUE THREAD

**Issue by brunosardinepi** [brunosardinepi/pagefund#389]
creating general campaign and donating

**Comment by dmortazavi** [comment]
created a campaign for PF Test 3 and donated $1. success. 

notes:
- i had to refresh the campaign page before my donation showed. not that big a deal
- got an email for my donation, but not on the campaign creation

**Comment by dmortazavi** [comment]
correction, campaign creation email came through about 5 min after

**Comment by dmortazavi** [comment]
Take out website link in page creation. if users want to add a website, they can go in and do later
- done

if on a page, you click on create a campaign, it prepopulates with page name on the campaign creation screen. this is good, but if you then search for another page, it takes this off. maybe we think about if a user is on a page and selects "create campaign" from that page, we take off the search for the parent page function. they are already where they need to be. i have no strong feelings, just an observation
- opened #410 for concept

no character limit display errors on campaign names, descriptions, comments, or report flag comments. created a voting campaign with a very long name and description. also, the "About" text did not wrap. just went on in one long string and eventually cut off with the browser window. after clicking off the campaign, it looks to have disappeared on the site, but you can still browse to it if you use the following URL                      (https://page.fund/pf-test-2/7/rrrrrrrfjnwojfsnlvekrjdsgfnweroljngsfoeqrjnlsrrrrrrrfjnwojfsnlvekrjdsgfnweroljngsfoeqrjnlsrrrrrrrfjnwojfsnlvekrjdsgfnweroljngsfoeqrjnlsrrrrrrrfjnwojfsnlvekrjdsgfnweroljngsfoeqrjnls/)
- fixed word wrap. agreed current limit of 255 is fine for now
