### ISSUE TITLE
live voting campaign test

### ISSUE THREAD

**Issue by brunosardinepi** [brunosardinepi/pagefund#390]
creating voting campaign and donating

**Comment by dmortazavi** [comment]
created a voting campaign for PF Test 3 and donated $1. success.

Notes:
- after creating the campaign, it directed me straight to the campaign manager dashboard, not the campaign homepage
- as of 5 min post creation, i received a donation email but not a campaign creation email

**Comment by dmortazavi** [comment]
correction, I have no received the campaign creation email

**Comment by dmortazavi** [comment]
Need to add a place to upload a profile picture upon page creation, as opposed to going through the page creation process and then going into setting to upload a picture
- agreed to leave out of page creation process

Take out website link in page creation. if users ant to add a website, they can go in and do later
- already done

if on a page, you click on create a campaign, it prepopulates with page name on the campaign creation screen. this is good, but if you then search for another page, it takes this off. maybe we think about if a user is on a page and selects "create campaign" from that page, we take off the search for the parent page function. they are already where they need to be. i have no strong feelings, just an observation 
- logged in #410 as concept
