### ISSUE TITLE
social authentication

### ISSUE THREAD

**Issue by brunosardinepi** [brunosardinepi/pagefund#391]
testing for signup and login using twitter, facebook, and google

**Comment by dmortazavi** [comment]
Signups with twitter, google and FB all work great. I think we may have issues with log-ins though. The work fine if each of the emails are unique, however, if i use the same email for my FB and google accts, then i can't login with the other. for example:

Login with google prompts me to re-enter my email. then once i do, it tells me that, "An account already exists with this e-mail address. Please sign in to that account first, then connect your Google account." I think this is bc i just created a Pagefund acct with FB, and the same email is tied to both. If i try to login with FB, then it works just fine. I was having the same problem but visa-versa prior to me having you delete my users on the back end. 

We may want to think about just limiting the sign up to traditional and fb only. Worth a discussion as people might forget which ones they signed up with if they haven't been back in a while

**Comment by brunosardinepi** [comment]
decided we'll build the view for managing social accounts and keep these 3 sites
