### ISSUE TITLE
Remove stripe emails upon donation

### ISSUE THREAD

**Issue by dmortazavi** [brunosardinepi/pagefund#402]
stripe sends a receipt to the sender (user) and a notice to the receiver (page), upon any donation to a page. look into if this can be disabled

**Comment by brunosardinepi** [comment]
stripe is sending these to admin@page.fund as a notification, these aren't actually going to customers. @dmortazavi can you confirm? check the sent to address on these and make sure it's whatever email you're using on the admin distro (i guess dustin@page.fund but idk who's in it right now)

**Comment by brunosardinepi** [comment]
![2018-02-07 07_45_59-dashboard](https://user-images.githubusercontent.com/22970115/35919508-f56464d0-0bda-11e8-9019-ad6958529b1f.png)

**Comment by brunosardinepi** [comment]
confirmed this is what's happening
