### ISSUE TITLE
Dustin Testing Notes - 2/10/2017

### ISSUE THREAD

**Issue by dmortazavi** [brunosardinepi/pagefund#432]
manage Page
- editing the name of a Page (PF Test 2) seems to have created a whole new duplicate page. Changed “PF Test 2” to “PF Test 2 - edited” and it created a whole new page for PF Test 2 - Edited. I also changed the description when i changed the name if that helps. i am not sure if the bank info copied over. can you see on the back end?
  - this new page that got created (PF Test 2 - edited) is showing a past campaign (the one with the very long name)
  - I tried to recreate the scenario with PF Test 3 and PF Test 4 and could not
  - can't recreate the issue
- ~~vanity URL should change if someone edits their page name. maybe need to discuss this as all previous links the user would have shared will die. since it is so easy to create on PF, maybe we just don’t allow the changing of names. personally, i am fine with that option~~
- vanity URL displays hyphens in the spaces 
  - #433 
- Invited another user to manage a page and adjusted combinations of access. when revoking analytics perms, analytics tab still showed and was accessible. when revoking the images perms, the images tab still shows but throws a 404 error. ideally, it just wouldnt show or would be grayed out
  - #435 
- for PF Test 3 - edited - edited twice manage page —> donations tab, the amount donated to a page displays as 0 even through there has been $2 donated via 2 campaigns. maybe it just takes some time to sync? donors and history display correctly. if this is just tracking the amount donated directly through the Page, then maybe we should consider taking it out of the donations tab as it is already listed in the analytics tab
  - may need a better label. this is saying there has been $0 donated directly to the page. if you go to the campaigns tab, you will probably see $2 donated to campaigns
  - #436

Creating a Campaign 
- maybe something to consider is attaching a name to a campaign to personalize it a little more. (ex: Garrett is raising money for the red cross)
  - need to consider that users don't need a name to start a campaign so this would open us up to things like "dungeonomics@gmail.com is raising money for..."

manage Campaign
- ~~vanity URL should change if someone edits their campaign name. maybe need to discuss this as all previous links the user would have shared will die. since it is so easy to create on PF, maybe we just don’t allow the changing of names~~
- vanity URL displays hyphens in the spaces 
  - #433
- Invited another user to manage a page and adjusted combinations of access. when revoking analytics perms, analytics tab still showed and was accessible. when revoking the images perms, the images tab still shows but throws a 404 error. ideally, it just wouldnt show or would be grayed out
  - #435

donation
- donations from a few days ago still have not hit the PF bank acct. wondering how long it takes to deposit funds. I remember us talking but can’t remember how often it deposits
  - #437
- if i type in a custom amount and also check a canned radio button, which takes precedence?
   - #427

Profile
- no need for users to have more than 1 picture. profile pic and thats it
  - #434 
- under my campaigns, maybe we can break it down into active and past
  - #438
- i think we should consider taking the "print" function out of the "donation history" section until we hammer out how that looks. won't need it till tax time next year anyways
  - #439

Invitations
- if i am logged in a user and i invite someone to sign up for PF that already has a user on PF, then it should stop me from doing so. currently it only stops me if i am trying to invite myself
  - #440
- if i am logged in as a page/campaign owner/manager, PF should stop me if i try to invite someone that is already listed as an owner/manager of that page/campaign
  - #440 

Sharing 
- sharing pages and campaigns on twitter and FB burner accts - works well but picture doesn’t show on my FB or twitter timeline. the picture is an empty default in the post
  - #441

**Comment by brunosardinepi** [comment]
digested and moved everything into its own issue
