### ISSUE TITLE
page dashboard donations label

### ISSUE THREAD

**Issue by brunosardinepi** [brunosardinepi/pagefund#436]
for PF Test 3 - edited - edited twice manage page —> donations tab, the amount donated to a page displays as 0 even through there has been $2 donated via 2 campaigns. maybe it just takes some time to sync? donors and history display correctly. if this is just tracking the amount donated directly through the Page, then maybe we should consider taking it out of the donations tab as it is already listed in the analytics tab
- may need a better label. this is saying there has been $0 donated directly to the page. if you go to the campaigns tab, you will probably see $2 donated to campaigns

**Comment by dmortazavi** [comment]
after some digging, i figured that was the case. updating the labels works for me
