### ISSUE TITLE
UAT Prep

### ISSUE THREAD

**Issue by dmortazavi** [brunosardinepi/pagefund#446]
Garrett,

Please complete the below actions in preparation for UAT. Users will see this script: https://docs.google.com/document/d/1LrF3jTaXvZZYqnSWIOIfNsPag-s8osLuw3_040e8R2w/edit?usp=sharing

create numerous donations to the UAT Test Page, UAT Test Campaign, and UAT Test Voting Campaign. Please have the Pagefundtesting user and some other dummy users (if possoble) be the donor. u: pagefundtesting@gmail.com  p: t3sting
- there needs to be various donations made to each dating back to the beginning of 2018 through present day
- at least one day in january needs to have multiple donations made to the page 

Please also remove any pages and campaigns that are not labeled "UAT". Once you are complete, all thats left should be the 1 UAT Page and 2 campaigns. i would remove these myself but i dont own any of the active pages

**Comment by brunosardinepi** [comment]
deleted all test/live pages except UAT
deleted all stripe customers (existing users will re-populate)
generated 100 donations for jan/feb on test page and each test campaign
