### ISSUE TITLE
add Page vs. Campaign info to the FAQ page

### ISSUE THREAD

**Issue by brunosardinepi** [brunosardinepi/pagefund#476]

**Comment by dmortazavi** [comment]
**What is the difference between a Page and a Campaign?**
A Page is for someone that runs an organization, or an individual, that is looking to raise funds for themselves. Anyone can visit a Page and donate directly to its owner. Pages are perpetual, and will stay active until the Page owner decides to take it down

A Campaign is for someone who is looking to raise funds on behalf of an existing Page. Anyone can visit a Campaign and donate to it. The funds will then funnel directly and automatically to the parent Page that it is benefiting. There is no need for a Campaign owner to hold or transfer funds. Unlike Pages, Campaigns are goal-based with a beginning and end date.

**Comment by brunosardinepi** [comment]
added
