### ISSUE TITLE
Add info on the “How it works” section for how to donate to a Page/Campaign

### ISSUE THREAD

**Issue by brunosardinepi** [brunosardinepi/pagefund#483]

**Comment by dmortazavi** [comment]
To donate to a Page or a Campaign, search for it on PageFund and click “Donate.” Select the amount you wish to donate, choose whether or not you want to make your donation anonymous, and enter your payment details. Sign up for a free account on PageFund to save your payment details for future use, or to set up a monthly recurring donation. Your donation will then be securely sent directly to the Page!
